// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

var Response = /* module */[];

var $$Error = /* module */[];

function end_(cb, req) {
  var cb$1 = function (err, x) {
    if (err !== null) {
      return Curry._1(cb, /* Error */Block.__(1, [err]));
    } else {
      return Curry._1(cb, /* Ok */Block.__(0, [x]));
    }
  };
  req.end(cb$1);
  return /* () */0;
}

exports.Response = Response;
exports.$$Error  = $$Error;
exports.end_     = end_;
/* No side effect */
